### ISSUE TITLE
Deleting Sets from a Workout Session

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#10]
WORKOUT SESSION<epic>

As a **User** I can **delete sets from a workout sessions** so I can **remove incorrectly documented sets**

**Acceptance criteria**
- [x] User can successfully remove sets from a workout session

**Tasks**
- [x] Create a View class
- [x] Define a method that removes a set from a workout session
- [x] Register view at URL
- [x] Testing
