### ISSUE TITLE
List of Workout sessions

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#11]
WORKOUT SESSION<epic>

As a **User** I can **see a list my workout sessions** so I can **see a summary of workouts and set goals for the next workout session**

**Acceptance criteria**
- [x] User can see a list their own workouts
- [x] The list is comprised of**name of the workout**, **name of exercise** in a set and **summarized results** of each set 

**Tasks**
- [x] Create View
- [x] Create template
- [x] Register at URL
