### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#12]
WORKOUT SESSION <epic>

As a **User** I can **use a timer in the workout** so I can **time my running and endurance exercises**

**Acceptance criteria**
- [x] User can use a Timer with a start/stop button in the window of the browser
- [x] Only workout sets that use exercises of type **RUNNING** or **ENDURANCE** provide a timer
- [x] Timer results are automatically inserted into the relevant field

**Tasks**
- [x] Create Javascript file with a class named Timer
- [x] Add methods start and stop to the Timer
- [x] Integrate the Timer in Workload templates
