### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#14]
As a **User** I can **navigate to all available sites** so I can **access the features of the application**

**Acceptance criteria**
- [x] Navigation Bar displays items for unauthenticated Users such as Login, Sign-Up 
- [x] Navigation Bar displays item for authenticated Users such as Exercises, Start Workout

**Tasks**
- [x] Register**django-allauth** in **INSTALLED_APPS** 
- [x] Register **django-allauth** in urls.py 
- [x] Copy the folder /lib/site-packages/allauth/templates to the project's template folder
- [x] Override the allauth default templates: login.html, logout.html and signup.html
- [x] Create a base template
- [x] Add Navigation Bar to the base template, that renders a different set of items depending on whether or not the user is authenticated
- [x] Test

**Comment by dimitri-edel** [comment]
Everything works!
