### ISSUE TITLE
Edit Workout Session

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#15]
As a **User** I can **edit a workout session** so I can **rename it or add other exercises to it**

**Acceptance criteria**
- [x] User can rename the name of Workout session
- [x] User can add exercises to the Workout session

**Tasks**
- [x] Define View
- [x] Create template
- [x] Register View at URL
