### ISSUE TITLE
Refactor the workload app

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#17]
During the first iteration a **workload** app was created. The workload model stores exercise sets of workout sessions. The problem with it is that it stores all types of exercise in one model, which makes it difficult to read and extend. It is better to create an individual app for every exercise type.

As a **developer** I can **easily add and change exercise types**

**Acceptance criteria**
- [x] Each exercise type has a separate app

**Tasks**
- [x] Create apps **weight_lifting**, **running** and **endurance**
- [x] Create models, forms, views, templates, and templates using the existing files in workload app
- [x] Alter workout.summaries.py to match the newly created models
