### ISSUE TITLE
Refactor the EditWorkout View and template

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#18]
**Issue** with the **current implementation** is that **renaming** a workout session and adding exercises to the workout are handled inside the same view. The template is using several django forms inside one HTML-form, which leads to a difficult to read type of code.

**Tasks**
- [x] Create View for Renaming Workouts
- [x] Create template for Renaming Workouts
- [x] Register view at URL
- [x] Link the URL to the **Rename** button in EditWorkout view
