### ISSUE TITLE
Refactor summaries.py in workout app

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#19]
**Problem** is that the entire logic is handled inside Summarizer class, which makes the code difficult to read. Most of the algorithms should be inside classes WorkoutSummary and ExerciseReport, each handling data that is relevant to them.

**Tasks**
- [x] Add methods to WorkoutSummay that handle data of type Workout
- [x] Add methods to ExerciseReport that handle data related to the Relationship WorkoutExercise and classes WeightLifting, Running, Endurance that are directly linked to that relationship
- [x] Adjust the code inside Summarizer.get_reports() according to the changes
