### ISSUE TITLE
Sign out

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#2]
AUTHENTICATION<epic>

As a **User** I can **successfully sign out** so I can **end the workout session**

**Acceptance criteria**
- [x] Session is ended 
- [x] Sing in icon is visible in the navigation bar

**Tasks**
- [x] Override default alluth logout template
