### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#3]
AUTHENTICATION<epic>

As a **new User** I can **register with the application** so I can **sign in and use the features of the application**

**Acceptance criteria**
- [x] Registration process creates a new User, whose credentials can be used to sign in
- [x] Look and feel of the form is consistent with the overall look and feel of the application

**Tasks**
- [x] Override the default template

**Comment by dimitri-edel** [comment]
Everything OK!
