### ISSUE TITLE
Define an exercise

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#4]
EXERCISE LIST<epic>

As a **User** I can **define an exercise** so I can **use it in my workout sessions**.

**Acceptance criteria**
- [x] User can name the exercise
- [x] User can assign a type to the exercise
- [x] User can select type from the following list: Weight-Lifting, Running, Endurance
- [x] Weight-Lifting exercise allows the User to document how many times they lift a certain weight in a particular set during a workout session
- [x] Running exercise allows the User to document how long a distance they could run in a particular set during a workout session
- [x] Endurance exercise allows the User to document how many repetitions over time they could do in a particular set during a workout session
- [x] User becomes owner of the exercise when committing to the database

**Tasks**
- [x] Create View
- [x] Check if the user is logged in 
- [x] Make User in the request the owner of the dataset
- [x] Create template with a form that has the fields: name, exercise type
- [x] Register view at URL
- [x] Test against the acceptance criteria
