### ISSUE TITLE
Edit exercise

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#5]
EXERCISE LIST<epic>

As a **User** I can **edit an exercise** so I can **change its name or type**

**Acceptance criteria**
- [x] User can rename an exercise
- [x] User can change type of an exercise

**Tasks**
- [x] Create View
- [x] Create template
- [x] Register view at URL
