### ISSUE TITLE
Delete Exercise

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#6]
EXERCISE LIST<epic>

As a **User** I can **delete an exercise** so I can **remove exercises that are useless to the user**.

**Acceptance criteria**
- [x] Exercises can be deleted if they have not been used in one of the existing workout sessions
- [x] User can only delete their own exercises

**Tasks**
- [x] Create View
- [x] Register at URL
- [x] Pass id of the exercise to the URL
