### ISSUE TITLE
User's Exercise List

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#7]
EXERCISE LIST<epic>

As a **User** I can **get a list of exercises that were defined by me** so I can **use them in my workout sessions**

**Acceptance criteria**
- [x] The list only contains exercises that were created by the given User
- [x] User can delete exercises from the list, if they are not used in any workouts
- [x] User can edit exercises from the list
- [x] There is a link in the navigation bar that allows users to open it

**Tasks**
- [x] Create View
- [x] Create template
- [x] Create a link to the edit page in the template
- [x] Create a link to the delete URL in the template
- [x] Register template at URL
- [x] Add link to the navigation bar
- [x] Test against the acceptance criteria
