### ISSUE TITLE
Create a Workout Session

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#8]
WORKOUT SESSION<epic>

As a **User** I can **start a workout session** so I can **document my workload in the journal**.

**Acceptance criteria**
- [x] User can name the workout session
- [x] Date on which the workout took place
- [x] Access to the data of individual workout sessions is only allowed for users who create them

**Tasks**
- [x] Define Model
- [x] Create View for creating a Workout
- [x] Create template
- [x] Register view at URL
