### ISSUE TITLE
Adding sets to a Workout session

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/dte-workout-app#9]
WORKOUT SESSION<epic>

As a **User** I can **add a set to an exercise in a workout session** so I can **document the workload that was done during a set**.

**Acceptance criteria**
- [x] User can select an exercise from the list of exercises that they have defined
- [x] The Set shows fields such as Repetitions, Weight, Distance or Time, based on the type of the selected exercise
- [x] Multiple sets can be added to a workout sessions

#4 

**Tasks**
- [x] Create View that lists the sets
- [x] Define a post method for adding a new set
- [x] Create template
- [x] Register view at URL
